### ISSUE TITLE
What may have caused the extra noise added to a face during inference after adapting the current code framework in liveTalking from ernerf to Synctalk?

### ISSUE THREAD

**Issue by EYcab** [lipku/LiveTalking#302]
![0](https://github.com/user-attachments/assets/2b14aab2-019e-4f74-a78d-ef929471e9b5)
The inference of my model based on SyncTalk work perfectly fine, but after adapting this model to liveTalking codes based on the ERNERF approach, there was noise added to her face. 

Please give me some hints on handling this issue. Thank you in advance.

**Comment by nguyenchiminhhieu** [comment]
@Deltaidiots  Hello,

I'm really excited to see this issue of yours! I'm also exploring the possibility of using the SyncTalk model instead of ER-NeRF as currently implemented in the repo. Could you guide me on how to make this transition?

I'm new to this, so detailed instructions would be incredibly helpful. Thank you so much for your kindness!

Also, if I would like to reach out to you for further discussion, what would be the best way to contact you?

Best regards,

**Comment by EYcab** [comment]
This is basically a matter of parameters setting issue
